### ISSUE TITLE
npm run serve throws eslint errors on vue templates

### ISSUE THREAD

**Issue by lukemalinowski** [mitre/heimdall-vue#38]
```
Module Warning (from ./node_modules/eslint-loader/index.js):
error: Parsing error: Unexpected token < at src/App.vue:1:1:
> 1 | <template>
    | ^
  2 |   <b-container fluid>
  3 |     <NavHeader/>
  4 |     <router-view/>


1 error found.
```

**Comment by lukemalinowski** [comment]
reproduce with 

```npm run lint```

**Comment by robthew** [comment]
This a false positive - there's nothing wrong with the template. It's really a problem between eslint and vue. If you google around, you'll find other people trying to turn off this warning. I haven't found one that works.

**Comment by lukemalinowski** [comment]
pushed up a fix, the vue eslint plugin wasnt activating, ill go through and work on the linter errors after the stand up

**Comment by lukemalinowski** [comment]
now we have something like
```
warning: Prop "title" should define at least its type (vue/require-prop-types) at src/components/CountCard.vue:35:13:
  33 |   export default {
  34 |     name: '',
> 35 |     props: ['title', 'explanation', 'fasIcon', 'colorVariant'],
     |             ^
  36 |     data () {
  37 |       return {
  38 |         store


warning: Prop "explanation" should define at least its type (vue/require-prop-types) at src/components/CountCard.vue:35:22:
  33 |   export default {
  34 |     name: '',
> 35 |     props: ['title', 'explanation', 'fasIcon', 'colorVariant'],
     |                      ^
  36 |     data () {
  37 |       return {
  38 |         store


warning: Prop "fasIcon" should define at least its type (vue/require-prop-types) at src/components/CountCard.vue:35:37:
  33 |   export default {
  34 |     name: '',
> 35 |     props: ['title', 'explanation', 'fasIcon', 'colorVariant'],
     |                                     ^
  36 |     data () {
  37 |       return {
  38 |         store


warning: Prop "colorVariant" should define at least its type (vue/require-prop-types) at src/components/CountCard.vue:35:48:
  33 |   export default {
  34 |     name: '',
> 35 |     props: ['title', 'explanation', 'fasIcon', 'colorVariant'],
     |                                                ^
  36 |     data () {
  37 |       return {
  38 |         store


warning: Prop "controls" should define at least its type (vue/require-prop-types) at src/components/DataTable.vue:60:11:
  58 | 
  59 | export default {
> 60 |   props: ['controls'],
     |           ^
  61 |   data() {
  62 |     return {
  63 |       headers: [


error: Expected to return a value in "getControls" computed property (vue/return-in-computed-property) at src/components/DataTable.vue:78:18:
  76 |       return store.getBindValue();
  77 |     },
> 78 |     getControls: function () {
     |                  ^
  79 |       if (isMounted == true) {
  80 |         var val = store.getControls();
  81 |         let vm = this;


error: 'index' is defined but never used (vue/no-unused-vars) at src/components/Treemap.vue:37:35:
  35 |               <!-- Generate each of the visible squares at a given zoom level (the current selected node) -->
  36 |               <g
> 37 |                 v-for="(children, index) in selectedNode._children"
     |                                   ^
  38 |                 v-if="selectedNode"
  39 |                 :key="'c_' + children.id"
  40 |                 class="children"


error: This 'v-if' should be moved to the wrapper element (vue/no-use-v-if-with-v-for) at src/components/Treemap.vue:38:17:
  36 |               <g
  37 |                 v-for="(children, index) in selectedNode._children"
> 38 |                 v-if="selectedNode"
     |                 ^
  39 |                 :key="'c_' + children.id"
  40 |                 class="children"
  41 |               >


warning: Attribute ":style" should go before "@click" (vue/attributes-order) at src/components/Treemap.vue:69:19:
  67 |                   :height="y(children.y1 - children.y0 + children.parent.y0)"
  68 |                   @click="selectNode"
> 69 |                   :style="{ fill: color(children.data) }"
     |                   ^
  70 |                 >
  71 |                   <!-- The title attribute -->
  72 |                   <title>{{ children.data.desc ? children.data.desc + ' | ' + children.data.count : children.data.count }}</title>


error: 'v-else' directives require no attribute value (vue/valid-v-else) at src/views/Home.vue:4:15:
  2 |   <AboutContent v-if="shouldShowAbout" />
  3 |   <SspContent v-else-if="shouldShowSSP" />
> 4 |   <BContainer v-else="shouldShowResults">
    |               ^
  5 |     <BRow>
  6 |       <BCardGroup deck>
  7 |         <CountCard

```
